apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: tverkon/auth
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/*
deploy:
  kubectl: {}
