apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: ticketing
build:
  # local:
  #   push: false
  artifacts:
    - image: tverkon/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        infer: ['*/*.js']
      #   manual:
      #     - src: 'src/**/*/ts'
      #       dest: .
    - image: tverkon/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        infer: ['*/*.js']
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/*
