apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: tverkon/auth
      context: auth
      sync:
        infer:
          - '*/*.js'
      docker:
        dockerfile: Dockerfile
    - image: tverkon/client
      context: client
      sync:
        infer:
          - '*/*.js'
      docker:
        dockerfile: Dockerfile
    - image: tverkon/tickets
      context: tickets
      sync:
        infer:
          - '*/*.js'
      docker:
        dockerfile: Dockerfile
    - image: tverkon/orders
      context: orders
      sync:
        infer:
          - '*/*.js'
      docker:
        dockerfile: Dockerfile
    - image: tverkon/expiration
      sync:
        infer:
          - '*/*.js'
      context: expiration
      docker:
        dockerfile: Dockerfile
    - image: tverkon/payments
      sync:
        infer:
          - '*/*.js'
      context: payments
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
